'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, Sparkles, Loader, X, Check } from 'lucide-react'
import { useTheme } from '../../../theme-provider'

const CATEGORIES = [
  { name: 'Travel', color: 'from-cyan-500 to-blue-500' },
  { name: 'Skills', color: 'from-violet-500 to-purple-500' },
  { name: 'Health', color: 'from-emerald-500 to-green-500' },
  { name: 'Adventure', color: 'from-orange-500 to-red-500' },
  { name: 'Personal', color: 'from-pink-500 to-rose-500' },
]

interface AIRecommendation {
  title: string
  why: string
  milestones: string[]
  timeframe: string
  estimatedBudget?: string
}

export default function AddGoalPage() {
  const router = useRouter()
  const { theme } = useTheme()
  const [isLoading, setIsLoading] = useState(false)
  const [aiLoading, setAiLoading] = useState(false)
  const [showAIModal, setShowAIModal] = useState(false)
  const [aiRecommendations, setAiRecommendations] = useState<AIRecommendation[]>([])
  const [selectedAIGoal, setSelectedAIGoal] = useState<AIRecommendation | null>(null)
  const [aiError, setAiError] = useState('')

  const [formData, setFormData] = useState({
    title: '',
    description: '',
    category: 'Travel',
    targetDate: '',
    budget: '',
    priority: 'Medium',
    difficulty: 'Medium',
    location: '',
    tags: '',
    visibility: 'Private'
  })

  const [milestones, setMilestones] = useState<string[]>([])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)

    try {
      const token = localStorage.getItem('token')
      
      const res = await fetch('/api/goals', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          ...formData,
          tags: formData.tags.split(',').map(t => t.trim()).filter(t => t),
          budget: formData.budget ? parseFloat(formData.budget) : null
        })
      })

      if (res.ok) {
        const goal = await res.json()
        
        // Add milestones if generated by AI
        if (milestones.length > 0) {
          for (const milestone of milestones) {
            await fetch(`/api/goals/${goal.id}/milestones`, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${token}`
              },
              body: JSON.stringify({ title: milestone })
            })
          }
        }

        router.push('/dashboard')
      } else {
        alert('Failed to create goal')
      }
    } catch (error) {
      alert('Error creating goal')
    } finally {
      setIsLoading(false)
    }
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target
    setFormData(prev => ({ ...prev, [name]: value }))
  }

  // ===== NEW: AI GENERATION FUNCTION =====
  const generateAIPlan = async () => {
    setAiLoading(true)
    setAiError('')
    setAiRecommendations([])

    try {
      const res = await fetch('/api/ai/recommend-goal', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    title: formData.title,
    description: formData.description,
    category: formData.category,
    budget: formData.budget,
    targetDate: formData.targetDate,
    location: formData.location,
    userGoals: []
  })
})

      const data = await res.json()
      if (!res.ok || !data.success || !Array.isArray(data.recommendations) || data.recommendations.length === 0) {
        setAiError(data.error || 'Failed to generate AI recommendations. Make sure GROQ API key is set in .env.local')
        return
      }

      setAiRecommendations(data.recommendations)
      setShowAIModal(true)
    } catch (error) {
      console.error('AI Error:', error)
      setAiError('Error connecting to AI. Check your GROQ_API_KEY in .env.local')
    } finally {
      setAiLoading(false)
    }
  }

  // ===== NEW: APPLY AI RECOMMENDATION =====
  const applyAIRecommendation = (rec: AIRecommendation) => {
    setFormData(prev => ({
      ...prev,
      title: rec.title,
      description: rec.why,
      tags: rec.timeframe ? `${rec.timeframe}, ${prev.tags}` : prev.tags,
      budget: rec.estimatedBudget || prev.budget
    }))
    setMilestones(rec.milestones || [])
    setShowAIModal(false)
    setSelectedAIGoal(rec)
  }

  const isDark = theme === 'dark'

  return (
    <div className={`min-h-screen ${isDark ? 'bg-slate-900 text-slate-200' : 'bg-gradient-to-br from-gray-50 via-slate-50 to-gray-100 text-gray-900'} p-8`}>
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <Link href="/dashboard" className={`inline-flex items-center gap-2 ${isDark ? 'text-slate-200' : 'text-blue-600 hover:text-blue-700'} mb-4`}>
            <ArrowLeft className="w-4 h-4" />
            Back to Dashboard
          </Link>
          <h1 className={`text-4xl font-bold ${isDark ? 'text-slate-100' : 'text-gray-900'} mb-2`}>Add New Goal</h1>
          <p className={`${isDark ? 'text-slate-300' : 'text-gray-600'}`}>Turn your dreams into actionable plans</p>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className={`${isDark ? 'bg-slate-800/60' : 'bg-white'} rounded-2xl shadow-xl p-8 space-y-6`}>
          
          {/* Selected AI Goal Badge */}
          {selectedAIGoal && (
            <div className={`p-4 rounded-xl border-2 flex items-center justify-between ${isDark ? 'bg-purple-500/10 border-purple-500/30' : 'bg-purple-100 border-purple-300'}`}>
              <div className="flex items-center gap-2">
                <Check className="w-5 h-5 text-purple-600" />
                <span className={`font-semibold ${isDark ? 'text-purple-300' : 'text-purple-700'}`}>
                  ✨ Goal enhanced with AI suggestions!
                </span>
              </div>
              <button
                type="button"
                onClick={() => {
                  setSelectedAIGoal(null)
                  setMilestones([])
                }}
                className="text-purple-600 hover:text-purple-700"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          )}

          {/* Title */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Goal Title</label>
            <input
              type="text"
              name="title"
              value={formData.title || ''}
              onChange={handleInputChange}
              placeholder="e.g., Visit Japan, Learn Guitar, Run a Marathon"
              required
              className={`w-full px-4 py-3 ${isDark ? 'bg-slate-700/60' : 'bg-gray-50'} border-2 border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 ${isDark ? 'text-slate-200' : 'text-black'}`}
            />
          </div>

          {/* Description */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Description</label>
            <textarea
              name="description"
              value={formData.description || ''}
              onChange={handleInputChange}
              placeholder="Tell us more about this goal..."
              rows={4}
              className={`w-full px-4 py-3 ${isDark ? 'bg-slate-700/60' : 'bg-gray-50'} border-2 border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 ${isDark ? 'text-slate-200' : 'text-black'}`}
            />
          </div>

          {/* Category */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-3">Category</label>
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
              {CATEGORIES.map((cat) => (
                <button
                  key={cat.name}
                  type="button"
                  onClick={() => {
                    setFormData(prev => ({ ...prev, category: cat.name }))
                    setSelectedAIGoal(null) // Reset AI suggestions when category changes
                    setMilestones([])
                  }}
                  className={`p-4 rounded-xl transition-all ${
                    formData.category === cat.name
                      ? `bg-gradient-to-br ${cat.color} text-white shadow-lg scale-105`
                      : `${isDark ? 'bg-slate-700 text-slate-200 hover:bg-slate-600' : 'bg-gray-100 text-gray-700 hover:bg-gray-200'}`
                  }`}
                >
                  <div className="text-sm font-medium">{cat.name}</div>
                </button>
              ))}
            </div>
          </div>

          {/* Row: Target Date, Budget */}
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Target Date</label>
              <input
                type="date"
                name="targetDate"
                value={formData.targetDate || ''}
                onChange={handleInputChange}
                className={`w-full px-4 py-3 ${isDark ? 'bg-slate-700/60' : 'bg-gray-50'} border-2 border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 ${isDark ? 'text-slate-200' : 'text-black'}`}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Budget (₹)</label>
              <input
                type="number"
                name="budget"
                value={formData.budget || ''}
                onChange={handleInputChange}
                placeholder="e.g., 200000"
                className={`w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 ${isDark ? 'bg-slate-700/60 text-slate-200' : 'bg-gray-50 text-black'}`}
              />
            </div>
          </div>

          {/* Row: Priority, Difficulty */}
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Priority</label>
              <select
                name="priority"
                value={formData.priority}
                onChange={handleInputChange}
                className={`w-full px-4 py-3 ${isDark ? 'bg-slate-700/60' : 'bg-gray-50'} border-2 border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 ${isDark ? 'text-slate-200' : 'text-black'}`}
              >
                <option>Low</option>
                <option>Medium</option>
                <option>High</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Difficulty</label>
              <select
                name="difficulty"
                value={formData.difficulty}
                onChange={handleInputChange}
                className={`w-full px-4 py-3 ${isDark ? 'bg-slate-700/60' : 'bg-gray-50'} border-2 border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 ${isDark ? 'text-slate-200' : 'text-black'}`}
              >
                <option>Easy</option>
                <option>Medium</option>
                <option>Hard</option>
              </select>
            </div>
          </div>

          {/* Location & Tags */}
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Location (Optional)</label>
              <input
                type="text"
                name="location"
                value={formData.location || ''}
                onChange={handleInputChange}
                placeholder="e.g., Tokyo, Japan"
                className={`w-full px-4 py-3 ${isDark ? 'bg-slate-700/60' : 'bg-gray-50'} border-2 border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 ${isDark ? 'text-slate-200' : 'text-black'}`}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Tags (comma separated)</label>
              <input
                type="text"
                name="tags"
                value={formData.tags}
                onChange={handleInputChange}
                placeholder="e.g., adventure, travel, expensive"
                className={`w-full px-4 py-3 ${isDark ? 'bg-slate-700/60' : 'bg-gray-50'} border-2 border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 ${isDark ? 'text-slate-200' : 'text-black'}`}
              />
            </div>
          </div>

          {/* Visibility */}
          <div className={`space-y-3 rounded-2xl border p-5 ${isDark ? 'border-slate-700 bg-slate-800/80' : 'border-gray-200 bg-gray-50/80'}`}>
            <p className={`text-sm font-semibold ${isDark ? 'text-slate-100' : 'text-gray-900'}`}>Make Public?</p>
            <div className="grid gap-3 sm:grid-cols-2">
              <label className={`cursor-pointer rounded-2xl border p-4 transition ${formData.visibility === 'Private' ? 'border-emerald-500 bg-emerald-500/10 text-emerald-100 shadow-inner' : isDark ? 'border-slate-600 bg-slate-700 text-slate-200' : 'border-gray-200 bg-white text-gray-700 hover:bg-gray-100'}`}>
                <input
                  type="radio"
                  name="visibility"
                  value="Private"
                  checked={formData.visibility === 'Private'}
                  onChange={handleInputChange}
                  className="mr-3"
                />
                <span className="font-medium">Private</span>
                <div className={`${isDark ? 'text-slate-400' : 'text-gray-500'} text-xs`}>Only me</div>
              </label>
              <label className={`cursor-pointer rounded-2xl border p-4 transition ${formData.visibility === 'Public' ? 'border-blue-500 bg-blue-500/10 text-blue-100 shadow-inner' : isDark ? 'border-slate-600 bg-slate-700 text-slate-200' : 'border-gray-200 bg-white text-gray-700 hover:bg-gray-100'}`}>
                <input
                  type="radio"
                  name="visibility"
                  value="Public"
                  checked={formData.visibility === 'Public'}
                  onChange={handleInputChange}
                  className="mr-3"
                />
                <span className="font-medium">Public</span>
                <div className={`${isDark ? 'text-slate-400' : 'text-gray-500'} text-xs`}>Everyone can see</div>
              </label>
            </div>
            <p className={`${isDark ? 'text-slate-400' : 'text-gray-500'} text-xs`}>Public goals appear in Explore</p>
          </div>

          {/* AI Generated Milestones Preview */}
          {milestones.length > 0 && (
            <div className={`rounded-2xl border p-6 ${isDark ? 'bg-blue-500/10 border-blue-500/30' : 'bg-blue-50 border-blue-200'}`}>
              <h3 className={`text-lg font-bold mb-4 flex items-center gap-2 ${isDark ? 'text-blue-300' : 'text-blue-900'}`}>
                <Sparkles className="w-5 h-5" />
                AI-Generated Milestones
              </h3>
              <div className="space-y-2">
                {milestones.map((milestone, idx) => (
                  <div key={idx} className={`p-3 rounded-lg flex items-center gap-2 ${isDark ? 'bg-slate-700/50' : 'bg-white'}`}>
                    <Check className="w-4 h-4 text-green-500" />
                    <span className={isDark ? 'text-slate-200' : 'text-gray-800'}>{milestone}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Buttons */}
          <div className="flex gap-4 pt-4">
            <button
              type="submit"
              disabled={isLoading}
              className="flex-1 py-3 bg-gradient-to-r from-blue-600 to-teal-600 text-white rounded-xl font-semibold hover:shadow-lg transition-all disabled:opacity-50"
            >
              {isLoading ? 'Creating...' : 'Create Goal'}
            </button>
            <button
              type="button"
              onClick={generateAIPlan}
              disabled={aiLoading}
              className="px-8 py-3 border-2 border-blue-600 text-blue-600 rounded-xl font-semibold hover:bg-blue-50 transition-all flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {aiLoading ? (
                <>
                  <Loader className="w-5 h-5 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
               {formData.title
  ? ' Refine My Goal'
  : ' Get AI Suggestions'}
                </>
              )}
            </button>
          </div>
        </form>
      </div>

      {/* ===== NEW: AI MODAL ===== */}
      {showAIModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className={`rounded-3xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl ${isDark ? 'bg-slate-900 border border-slate-700' : 'bg-white'}`}>
            
            {/* Header */}
            <div className={`sticky top-0 flex items-center justify-between p-6 border-b ${isDark ? 'bg-slate-900 border-slate-700' : 'bg-white border-gray-200'}`}>
              <div className="flex items-center gap-3">
                <Sparkles className="w-6 h-6 text-purple-500 animate-spin" />
                <h2 className={`text-2xl font-bold ${isDark ? 'text-slate-100' : 'text-gray-900'}`}>
                  AI Goal Recommendations
                </h2>
              </div>
              <button
                onClick={() => setShowAIModal(false)}
                className={`p-2 rounded-lg transition-colors ${isDark ? 'hover:bg-slate-800' : 'hover:bg-gray-100'}`}
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            {/* Content */}
            <div className="p-6 space-y-6">
              {aiError && (
                <div className={`p-4 rounded-xl border-2 ${isDark ? 'bg-red-500/10 border-red-500/30 text-red-300' : 'bg-red-100 border-red-300 text-red-800'}`}>
                  ⚠️ {aiError}
                </div>
              )}

              {aiRecommendations.length === 0 && !aiError && (
                <div className="text-center py-8">
                  <Loader className="w-8 h-8 animate-spin mx-auto mb-4 text-purple-500" />
                  <p className={isDark ? 'text-slate-300' : 'text-gray-700'}>Generating recommendations...</p>
                </div>
              )}

              {aiRecommendations.map((rec, i) => (
                <div
                  key={i}
                  className={`p-6 rounded-2xl border-2 cursor-pointer transition-all hover:shadow-lg ${isDark ? 'bg-slate-800/50 border-purple-500/30 hover:border-purple-500' : 'bg-purple-50 border-purple-200 hover:border-purple-400'}`}
                >
                  <div className="flex items-start justify-between mb-4">
                    <div>
                      <h3 className={`text-xl font-bold mb-2 ${isDark ? 'text-slate-100' : 'text-gray-900'}`}>
                        {rec.title}
                      </h3>
                      <p className={`${isDark ? 'text-slate-300' : 'text-gray-700'}`}>
                        {rec.why}
                      </p>
                    </div>
                  </div>

                  {/* Timeframe & Budget */}
                  <div className="grid grid-cols-2 gap-4 mb-4 pb-4 border-b">
                    <div>
                      <p className={`text-xs font-semibold ${isDark ? 'text-slate-400' : 'text-gray-600'}`}>Timeline</p>
                      <p className={`font-bold ${isDark ? 'text-slate-100' : 'text-gray-900'}`}>{rec.timeframe}</p>
                    </div>
                    {rec.estimatedBudget && (
                      <div>
                        <p className={`text-xs font-semibold ${isDark ? 'text-slate-400' : 'text-gray-600'}`}>Est. Budget</p>
                        <p className={`font-bold ${isDark ? 'text-slate-100' : 'text-gray-900'}`}>{rec.estimatedBudget}</p>
                      </div>
                    )}
                  </div>

                  {/* Milestones */}
                  {rec.milestones && rec.milestones.length > 0 && (
                    <div className="mb-4">
                      <p className={`text-sm font-semibold mb-3 ${isDark ? 'text-slate-300' : 'text-gray-700'}`}>
                        Key Milestones:
                      </p>
                      <ul className="space-y-2">
                        {rec.milestones.map((m, j) => (
                          <li key={j} className={`text-sm flex items-start gap-2 ${isDark ? 'text-slate-300' : 'text-gray-700'}`}>
                            <span className="text-green-500 font-bold mt-0.5">✓</span>
                            <span>{m}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Select Button */}
                  <button
                    onClick={() => applyAIRecommendation(rec)}
                    className="w-full mt-4 px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-xl font-bold hover:shadow-lg transition-all flex items-center justify-center gap-2"
                  >
                    <Check className="w-5 h-5" />
                    Use This Goal
                  </button>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
